import { f } from './formula';
import type { BaseMetric, DerivedMetric, MetricDef } from './types';

/**
 * The metric registry.
 *
 * Metric ids encode their BUCKETING RULE where it matters: `revenue.net@orderdate` is
 * restated when a refund lands 40 days later; `revenue.net@cashdate` buckets on the date
 * money actually moved and is never restated. Finance wants one, merchandising wants the
 * other, and forcing a single number to serve both is the single largest source of
 * "your report doesn't match my spreadsheet". Making it a type-level choice means nobody
 * can be vague about it.
 *
 * Never rename an id. Add the new one and mark the old `deprecated`.
 */

const base = (m: Omit<BaseMetric, 'kind'>): BaseMetric => ({ kind: 'base', ...m });
const derived = (m: Omit<DerivedMetric, 'kind'>): DerivedMetric => ({ kind: 'derived', ...m });

const MONEY = { style: 'money' } as const;
const INT = { style: 'integer' } as const;
const PCT = { style: 'percent', precision: 2 } as const;
const DEC = { style: 'decimal', precision: 2 } as const;

const defs: MetricDef[] = [
  // ── Orders and revenue (commerce, materialized) ─────────────────────────────────
  base({
    id: 'orders.count@orderdate',
    labelKey: 'metric.orders',
    valueType: 'count',
    aggregation: 'sum',
    additive: { overTime: true, overDimensions: true },
    minGrain: 'day',
    domains: ['commerce'],
    format: INT,
    higherIsBetter: true,
    nullSemantics: 'zero',
  }),
  base({
    id: 'revenue.gross@orderdate',
    labelKey: 'metric.revenueGross',
    descriptionKey: 'metric.revenueGross.description',
    valueType: 'money',
    aggregation: 'sum',
    additive: { overTime: true, overDimensions: true },
    minGrain: 'day',
    currencyScoped: true,
    domains: ['commerce'],
    format: MONEY,
    higherIsBetter: true,
    nullSemantics: 'zero',
  }),
  base({
    id: 'revenue.net@orderdate',
    labelKey: 'metric.revenueNet',
    descriptionKey: 'metric.revenueNet.description',
    valueType: 'money',
    aggregation: 'sum',
    additive: { overTime: true, overDimensions: true },
    minGrain: 'day',
    currencyScoped: true,
    domains: ['commerce'],
    format: MONEY,
    higherIsBetter: true,
    nullSemantics: 'zero',
  }),
  base({
    id: 'revenue.net@cashdate',
    labelKey: 'metric.revenueNetCash',
    descriptionKey: 'metric.revenueNetCash.description',
    valueType: 'money',
    aggregation: 'sum',
    additive: { overTime: true, overDimensions: true },
    minGrain: 'day',
    currencyScoped: true,
    domains: ['commerce'],
    format: MONEY,
    higherIsBetter: true,
    nullSemantics: 'zero',
  }),
  base({
    id: 'discount.value@orderdate',
    labelKey: 'metric.discountValue',
    valueType: 'money',
    aggregation: 'sum',
    additive: { overTime: true, overDimensions: true },
    minGrain: 'day',
    currencyScoped: true,
    domains: ['commerce'],
    format: MONEY,
    higherIsBetter: false,
    nullSemantics: 'zero',
  }),
  base({
    id: 'shipping.revenue@orderdate',
    labelKey: 'metric.shippingRevenue',
    valueType: 'money',
    aggregation: 'sum',
    additive: { overTime: true, overDimensions: true },
    minGrain: 'day',
    currencyScoped: true,
    domains: ['commerce'],
    format: MONEY,
    nullSemantics: 'zero',
  }),
  base({
    id: 'tax.collected@orderdate',
    labelKey: 'metric.taxCollected',
    valueType: 'money',
    aggregation: 'sum',
    additive: { overTime: true, overDimensions: true },
    minGrain: 'day',
    currencyScoped: true,
    domains: ['commerce'],
    format: MONEY,
    nullSemantics: 'zero',
  }),
  base({
    id: 'units.sold@orderdate',
    labelKey: 'metric.unitsSold',
    valueType: 'count',
    aggregation: 'sum',
    additive: { overTime: true, overDimensions: true },
    minGrain: 'day',
    domains: ['commerce'],
    format: INT,
    higherIsBetter: true,
    nullSemantics: 'zero',
  }),
  base({
    id: 'lines.count@orderdate',
    labelKey: 'metric.linesCount',
    valueType: 'count',
    aggregation: 'sum',
    additive: { overTime: true, overDimensions: true },
    minGrain: 'day',
    domains: ['commerce'],
    format: INT,
    nullSemantics: 'zero',
  }),

  // ── Refunds and returns ────────────────────────────────────────────────────────
  base({
    id: 'refunds.value@cashdate',
    labelKey: 'metric.refundsValue',
    valueType: 'money',
    aggregation: 'sum',
    additive: { overTime: true, overDimensions: true },
    minGrain: 'day',
    currencyScoped: true,
    domains: ['commerce'],
    format: MONEY,
    higherIsBetter: false,
    nullSemantics: 'zero',
  }),
  base({
    id: 'returns.units@orderdate',
    labelKey: 'metric.returnsUnits',
    valueType: 'count',
    aggregation: 'sum',
    additive: { overTime: true, overDimensions: true },
    minGrain: 'day',
    domains: ['commerce', 'oms'],
    format: INT,
    higherIsBetter: false,
    nullSemantics: 'zero',
  }),

  // ── Customers ─────────────────────────────────────────────────────────────────
  base({
    id: 'customers.new@orderdate',
    labelKey: 'metric.customersNew',
    valueType: 'count',
    aggregation: 'sum',
    additive: { overTime: true, overDimensions: true },
    minGrain: 'day',
    domains: ['commerce'],
    format: INT,
    higherIsBetter: true,
    nullSemantics: 'zero',
  }),
  base({
    id: 'customers.active@orderdate',
    labelKey: 'metric.customersActive',
    descriptionKey: 'metric.customersActive.description',
    valueType: 'count',
    // NOT summable across time: monthly uniques are not the sum of daily uniques.
    aggregation: 'countDistinct',
    additive: { overTime: false, overDimensions: false },
    minGrain: 'day',
    domains: ['commerce'],
    format: INT,
    higherIsBetter: true,
    nullSemantics: 'zero',
  }),
  base({
    id: 'customers.cohortSize',
    labelKey: 'metric.cohortSize',
    valueType: 'count',
    aggregation: 'sum',
    additive: { overTime: false, overDimensions: true },
    domains: ['commerce'],
    format: INT,
    nullSemantics: 'zero',
  }),
  base({
    id: 'customers.retained',
    labelKey: 'metric.customersRetained',
    valueType: 'count',
    aggregation: 'sum',
    additive: { overTime: false, overDimensions: true },
    domains: ['commerce'],
    format: INT,
    higherIsBetter: true,
    // A cohort three months old has no month-six cell. Zero would be a lie.
    nullSemantics: 'null',
  }),

  // ── Catalogue and inventory (live) ────────────────────────────────────────────
  base({
    id: 'products.count',
    labelKey: 'metric.productsCount',
    valueType: 'count',
    aggregation: 'sum',
    additive: { overTime: false, overDimensions: true },
    domains: ['commerce'],
    format: INT,
    nullSemantics: 'zero',
  }),
  base({
    id: 'variants.count',
    labelKey: 'metric.variantsCount',
    valueType: 'count',
    aggregation: 'sum',
    additive: { overTime: false, overDimensions: true },
    domains: ['commerce'],
    format: INT,
    nullSemantics: 'zero',
  }),
  base({
    id: 'price.min',
    labelKey: 'metric.priceMin',
    valueType: 'money',
    aggregation: 'min',
    additive: { overTime: false, overDimensions: false },
    currencyScoped: true,
    domains: ['commerce'],
    format: MONEY,
    nullSemantics: 'null',
  }),
  base({
    id: 'price.max',
    labelKey: 'metric.priceMax',
    valueType: 'money',
    aggregation: 'max',
    additive: { overTime: false, overDimensions: false },
    currencyScoped: true,
    domains: ['commerce'],
    format: MONEY,
    nullSemantics: 'null',
  }),
  base({
    id: 'price.mean',
    labelKey: 'metric.priceMean',
    valueType: 'money',
    aggregation: 'avg',
    additive: { overTime: false, overDimensions: false },
    currencyScoped: true,
    domains: ['commerce'],
    format: MONEY,
    nullSemantics: 'null',
  }),
  base({
    id: 'inventory.available',
    labelKey: 'metric.inventoryAvailable',
    valueType: 'count',
    aggregation: 'sum',
    additive: { overTime: false, overDimensions: true },
    domains: ['commerce', 'erp'],
    format: INT,
    nullSemantics: 'zero',
  }),

  // ── Web analytics ─────────────────────────────────────────────────────────────
  base({
    id: 'sessions.count',
    labelKey: 'metric.sessions',
    valueType: 'count',
    aggregation: 'sum',
    additive: { overTime: true, overDimensions: true },
    minGrain: 'day',
    domains: ['web-analytics'],
    format: INT,
    higherIsBetter: true,
    nullSemantics: 'zero',
  }),
  base({
    id: 'users.active',
    labelKey: 'metric.activeUsers',
    valueType: 'count',
    aggregation: 'countDistinct',
    additive: { overTime: false, overDimensions: false },
    minGrain: 'day',
    domains: ['web-analytics'],
    format: INT,
    higherIsBetter: true,
    nullSemantics: 'zero',
  }),
  base({
    id: 'pageviews.count',
    labelKey: 'metric.pageviews',
    valueType: 'count',
    aggregation: 'sum',
    additive: { overTime: true, overDimensions: true },
    minGrain: 'day',
    domains: ['web-analytics'],
    format: INT,
    nullSemantics: 'zero',
  }),
  base({
    id: 'productviews.count',
    labelKey: 'metric.productViews',
    valueType: 'count',
    aggregation: 'sum',
    additive: { overTime: true, overDimensions: true },
    minGrain: 'day',
    domains: ['web-analytics'],
    format: INT,
    higherIsBetter: true,
    nullSemantics: 'zero',
  }),
  base({
    id: 'addtocart.count',
    labelKey: 'metric.addToCarts',
    valueType: 'count',
    aggregation: 'sum',
    additive: { overTime: true, overDimensions: true },
    minGrain: 'day',
    domains: ['web-analytics'],
    format: INT,
    higherIsBetter: true,
    nullSemantics: 'zero',
  }),
  base({
    id: 'checkoutstart.count',
    labelKey: 'metric.checkoutStarts',
    valueType: 'count',
    aggregation: 'sum',
    additive: { overTime: true, overDimensions: true },
    minGrain: 'day',
    domains: ['web-analytics'],
    format: INT,
    higherIsBetter: true,
    nullSemantics: 'zero',
  }),
  base({
    id: 'searches.count',
    labelKey: 'metric.searches',
    valueType: 'count',
    aggregation: 'sum',
    additive: { overTime: true, overDimensions: true },
    minGrain: 'day',
    domains: ['web-analytics'],
    format: INT,
    nullSemantics: 'zero',
  }),
  base({
    id: 'searches.zeroResult',
    labelKey: 'metric.zeroResultSearches',
    valueType: 'count',
    aggregation: 'sum',
    additive: { overTime: true, overDimensions: true },
    minGrain: 'day',
    domains: ['web-analytics'],
    format: INT,
    higherIsBetter: false,
    nullSemantics: 'zero',
  }),

  // ── Cost and margin (ERP / warehouse) ────────────────────────────────────────
  base({
    id: 'cost.goods@orderdate',
    sensitivity: 'financials',
    labelKey: 'metric.costOfGoods',
    valueType: 'money',
    aggregation: 'sum',
    additive: { overTime: true, overDimensions: true },
    minGrain: 'day',
    currencyScoped: true,
    domains: ['erp', 'warehouse'],
    format: MONEY,
    nullSemantics: 'null',
  }),
  base({
    id: 'marketing.spend',
    sensitivity: 'financials',
    labelKey: 'metric.marketingSpend',
    valueType: 'money',
    aggregation: 'sum',
    additive: { overTime: true, overDimensions: true },
    minGrain: 'day',
    currencyScoped: true,
    domains: ['warehouse'],
    format: MONEY,
    nullSemantics: 'null',
  }),

  // ── Fulfilment (OMS) ─────────────────────────────────────────────────────────
  base({
    id: 'shipments.count',
    labelKey: 'metric.shipments',
    valueType: 'count',
    aggregation: 'sum',
    additive: { overTime: true, overDimensions: true },
    minGrain: 'day',
    domains: ['commerce', 'oms'],
    format: INT,
    nullSemantics: 'zero',
  }),
  base({
    id: 'shipments.onTime',
    labelKey: 'metric.shipmentsOnTime',
    valueType: 'count',
    aggregation: 'sum',
    additive: { overTime: true, overDimensions: true },
    minGrain: 'day',
    domains: ['commerce', 'oms'],
    format: INT,
    higherIsBetter: true,
    nullSemantics: 'zero',
  }),
  base({
    id: 'fulfilment.pickToShipSeconds',
    labelKey: 'metric.pickToShip',
    valueType: 'duration_s',
    aggregation: 'avg',
    additive: { overTime: false, overDimensions: false },
    minGrain: 'day',
    domains: ['oms'],
    format: { style: 'duration' },
    higherIsBetter: false,
    nullSemantics: 'null',
  }),
  base({
    id: 'supplier.fillRate',
    labelKey: 'metric.supplierFillRate',
    valueType: 'ratio',
    aggregation: 'avg',
    additive: { overTime: false, overDimensions: false },
    domains: ['erp'],
    format: PCT,
    higherIsBetter: true,
    nullSemantics: 'null',
  }),

  // ── Promotions ───────────────────────────────────────────────────────────────
  base({
    id: 'discount.redemptions',
    labelKey: 'metric.discountRedemptions',
    valueType: 'count',
    aggregation: 'sum',
    additive: { overTime: true, overDimensions: true },
    minGrain: 'day',
    domains: ['commerce'],
    format: INT,
    nullSemantics: 'zero',
  }),
  base({
    id: 'orders.promoted@orderdate',
    labelKey: 'metric.ordersWithPromotion',
    valueType: 'count',
    aggregation: 'sum',
    additive: { overTime: true, overDimensions: true },
    minGrain: 'day',
    domains: ['commerce'],
    format: INT,
    nullSemantics: 'zero',
  }),

  // ══ Derived — evaluated in the gateway AFTER aggregation. Ratio of sums, never
  //    sum of ratios. ═════════════════════════════════════════════════════════════
  derived({
    id: 'aov@orderdate',
    labelKey: 'metric.aov',
    valueType: 'money',
    evaluation: 'postAggregate',
    formula: f.safeRatio(f.ref('revenue.net@orderdate'), f.ref('orders.count@orderdate')),
    domains: ['commerce'],
    format: MONEY,
    higherIsBetter: true,
    nullSemantics: 'null',
  }),
  derived({
    id: 'upt@orderdate',
    labelKey: 'metric.unitsPerTransaction',
    valueType: 'ratio',
    evaluation: 'postAggregate',
    formula: f.safeRatio(f.ref('units.sold@orderdate'), f.ref('orders.count@orderdate')),
    domains: ['commerce'],
    format: DEC,
    higherIsBetter: true,
    nullSemantics: 'null',
  }),
  derived({
    id: 'discount.rate@orderdate',
    labelKey: 'metric.discountRate',
    valueType: 'percent',
    evaluation: 'postAggregate',
    formula: f.safeRatio(f.ref('discount.value@orderdate'), f.ref('revenue.gross@orderdate')),
    domains: ['commerce'],
    format: PCT,
    higherIsBetter: false,
    nullSemantics: 'null',
  }),
  derived({
    id: 'refund.rate',
    labelKey: 'metric.refundRate',
    valueType: 'percent',
    evaluation: 'postAggregate',
    formula: f.safeRatio(f.ref('refunds.value@cashdate'), f.ref('revenue.net@orderdate')),
    domains: ['commerce'],
    format: PCT,
    higherIsBetter: false,
    nullSemantics: 'null',
  }),
  derived({
    id: 'return.rate',
    labelKey: 'metric.returnRate',
    valueType: 'percent',
    evaluation: 'postAggregate',
    formula: f.safeRatio(f.ref('returns.units@orderdate'), f.ref('units.sold@orderdate')),
    domains: ['commerce', 'oms'],
    format: PCT,
    higherIsBetter: false,
    nullSemantics: 'null',
  }),
  derived({
    id: 'margin.gross@orderdate',
    sensitivity: 'financials',
    labelKey: 'metric.grossMargin',
    valueType: 'money',
    evaluation: 'postAggregate',
    formula: f.sub(f.ref('revenue.net@orderdate'), f.ref('cost.goods@orderdate')),
    domains: ['commerce', 'erp'],
    format: MONEY,
    higherIsBetter: true,
    nullSemantics: 'null',
  }),
  derived({
    id: 'margin.rate@orderdate',
    sensitivity: 'financials',
    labelKey: 'metric.grossMarginRate',
    valueType: 'percent',
    evaluation: 'postAggregate',
    formula: f.safeRatio(
      f.sub(f.ref('revenue.net@orderdate'), f.ref('cost.goods@orderdate')),
      f.ref('revenue.net@orderdate')
    ),
    domains: ['commerce', 'erp'],
    format: PCT,
    higherIsBetter: true,
    nullSemantics: 'null',
  }),
  // The canonical cross-source metric: orders from commerce, sessions from web analytics.
  derived({
    id: 'conversion.rate',
    labelKey: 'metric.conversionRate',
    descriptionKey: 'metric.conversionRate.description',
    valueType: 'percent',
    evaluation: 'postAggregate',
    formula: f.safeRatio(f.ref('orders.count@orderdate'), f.ref('sessions.count')),
    domains: ['commerce', 'web-analytics'],
    requiresConformed: ['date', 'country', 'device'],
    format: PCT,
    higherIsBetter: true,
    nullSemantics: 'null',
  }),
  derived({
    id: 'revenue.perSession',
    labelKey: 'metric.revenuePerSession',
    valueType: 'money',
    evaluation: 'postAggregate',
    formula: f.safeRatio(f.ref('revenue.net@orderdate'), f.ref('sessions.count')),
    domains: ['commerce', 'web-analytics'],
    requiresConformed: ['date', 'country', 'device'],
    format: MONEY,
    higherIsBetter: true,
    nullSemantics: 'null',
  }),
  derived({
    id: 'addtocart.rate',
    labelKey: 'metric.addToCartRate',
    valueType: 'percent',
    evaluation: 'postAggregate',
    formula: f.safeRatio(f.ref('addtocart.count'), f.ref('productviews.count')),
    domains: ['web-analytics'],
    format: PCT,
    higherIsBetter: true,
    nullSemantics: 'null',
  }),
  derived({
    id: 'checkout.completionRate',
    labelKey: 'metric.checkoutCompletionRate',
    valueType: 'percent',
    evaluation: 'postAggregate',
    formula: f.safeRatio(f.ref('orders.count@orderdate'), f.ref('checkoutstart.count')),
    domains: ['commerce', 'web-analytics'],
    requiresConformed: ['date'],
    format: PCT,
    higherIsBetter: true,
    nullSemantics: 'null',
  }),
  derived({
    id: 'searches.zeroResultRate',
    labelKey: 'metric.zeroResultRate',
    valueType: 'percent',
    evaluation: 'postAggregate',
    formula: f.safeRatio(f.ref('searches.zeroResult'), f.ref('searches.count')),
    domains: ['web-analytics'],
    format: PCT,
    higherIsBetter: false,
    nullSemantics: 'null',
  }),
  derived({
    id: 'retention.rate',
    labelKey: 'metric.retentionRate',
    valueType: 'percent',
    evaluation: 'postAggregate',
    formula: f.safeRatio(f.ref('customers.retained'), f.ref('customers.cohortSize')),
    domains: ['commerce'],
    format: PCT,
    higherIsBetter: true,
    nullSemantics: 'null',
  }),
  derived({
    id: 'roas',
    sensitivity: 'financials',
    labelKey: 'metric.roas',
    valueType: 'ratio',
    evaluation: 'postAggregate',
    formula: f.safeRatio(f.ref('revenue.net@orderdate'), f.ref('marketing.spend')),
    domains: ['commerce', 'warehouse'],
    requiresConformed: ['date'],
    format: DEC,
    higherIsBetter: true,
    nullSemantics: 'null',
  }),
  derived({
    id: 'cac',
    sensitivity: 'financials',
    labelKey: 'metric.cac',
    valueType: 'money',
    evaluation: 'postAggregate',
    formula: f.safeRatio(f.ref('marketing.spend'), f.ref('customers.new@orderdate')),
    domains: ['commerce', 'warehouse'],
    requiresConformed: ['date'],
    format: MONEY,
    higherIsBetter: false,
    nullSemantics: 'null',
  }),
  derived({
    id: 'dispatch.onTimeRate',
    labelKey: 'metric.onTimeDispatchRate',
    valueType: 'percent',
    evaluation: 'postAggregate',
    formula: f.safeRatio(f.ref('shipments.onTime'), f.ref('shipments.count')),
    domains: ['commerce', 'oms'],
    format: PCT,
    higherIsBetter: true,
    nullSemantics: 'null',
  }),
  derived({
    id: 'promotion.penetration',
    labelKey: 'metric.promotionPenetration',
    valueType: 'percent',
    evaluation: 'postAggregate',
    formula: f.safeRatio(f.ref('orders.promoted@orderdate'), f.ref('orders.count@orderdate')),
    domains: ['commerce'],
    format: PCT,
    nullSemantics: 'null',
  }),
];

export const METRICS: Readonly<Record<string, MetricDef>> = Object.freeze(
  Object.fromEntries(defs.map((m) => [m.id, Object.freeze(m)]))
);

export const getMetric = (id: string): MetricDef | undefined => METRICS[id];

export const isMoneyMetric = (id: string): boolean => METRICS[id]?.valueType === 'money';

export const BASE_METRIC_IDS: readonly string[] = Object.freeze(
  defs.filter((m): m is BaseMetric => m.kind === 'base').map((m) => m.id)
);

export const DERIVED_METRIC_IDS: readonly string[] = Object.freeze(
  defs.filter((m): m is DerivedMetric => m.kind === 'derived').map((m) => m.id)
);
