process.env.ENABLE_NEW_JSX_TRANSFORM = 'true';

const graphqlPlugin = require('@graphql-eslint/eslint-plugin');
const mcAppConfig = require('@commercetools-frontend/eslint-config-mc-app');

module.exports = [
  {
    /**
     * `src/shared` and `src/shared-node` are GENERATED by scripts/sync-shared.mjs from the
     * repo's shared packages, which own their own lint and format config. Linting the copy
     * here would report thousands of style differences that cannot be fixed in place —
     * they would just be overwritten on the next sync — and would bury real findings.
     */
    ignores: ['src/shared/**', 'src/shared-node/**', 'public/**', 'dist/**'],
  },
  ...mcAppConfig,
  {
    files: ['**/*.ctp.graphql'],
    plugins: { '@graphql-eslint': graphqlPlugin },
    languageOptions: {
      parser: graphqlPlugin,
      parserOptions: {
        graphQLConfig: {
          schema: './schemas/ctp.json',
        },
      },
    },
    rules: {
      '@graphql-eslint/known-type-names': 'error',
      '@graphql-eslint/known-argument-names': 'error',
      '@graphql-eslint/known-directives': 'error',
      '@graphql-eslint/scalar-leafs': 'error',
    },
  },
  {
    files: ['eslint.config.js'],
    rules: { 'import/extensions': 'off' },
  },
];
